# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('main_photo', models.ImageField(upload_to='')),
                ('detail_photo', models.ImageField(upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloth_category', models.CharField(choices=[('TOP', 'top'), ('BOTTOM', 'bottom'), ('CODY', 'cody')], default='CODY', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product_bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('main_photo', models.ImageField(upload_to='')),
                ('detail_photo', models.ImageField(upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloth_category', models.CharField(choices=[('TOP', 'top'), ('BOTTOM', 'bottom'), ('CODY', 'cody')], default='BOTTOM', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product_top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('main_photo', models.ImageField(upload_to='')),
                ('detail_photo', models.ImageField(upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloth_category', models.CharField(choices=[('TOP', 'top'), ('BOTTOM', 'bottom'), ('CODY', 'cody')], default='TOP', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_bottom',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product_bottom'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_top',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product_top'),
        ),
    ]
