# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_cloth_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('main_photo', models.ImageField(upload_to='')),
                ('detail_photo', models.ImageField(upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloth_category', models.CharField(choices=[('TOP', 'top'), ('BOTTOM', 'bottom'), ('CODY', 'cody')], default='CODY', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='product_top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('main_photo', models.ImageField(upload_to='')),
                ('detail_photo', models.ImageField(upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloth_category', models.CharField(choices=[('TOP', 'top'), ('BOTTOM', 'bottom'), ('CODY', 'cody')], default='CODY', max_length=6)),
            ],
        ),
    ]
